apiVersion: batch/v1
kind: CronJob
metadata:
  name: pull-google-page-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: curlalpine
              image: alpine/curl
              command: ["curl", "https://www.google.com"]
