apiVersion: v1
kind: ConfigMap
metadata:
  name: log-config
data:
  log_level.conf: |
    # Podemos montar un configmap como volumen
    log_level=INFO
    algo_que_me_invento=ESTO
    otra_cosa=ESTO_TAMBIEN
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume
spec:
  containers:
    - name: test
      image: busybox
      command:
        [
          "sh",
          "-c",
          'echo "Contenido de del volumen:" && ls -al /etc/config && tail -f /dev/null',
        ]
      volumeMounts:
        - name: config-vol
          mountPath: /etc/config/log_level
  volumes:
    - name: config-vol
      configMap:
        name: log-config
        items:
          - key: log_level.conf
            path: log_level.conf
