apiVersion: v1
kind: Pod
metadata:
  name: wp-pod
  labels:
    app: blog
spec:
  containers:
    - name: wp
      image: wordpress:latest
      ports:
        - containerPort: 80
      env:
        - name: WORDPRESS_DB_HOST
          value: mysql-pod
        - name: WORDPRESS_DB_USER
          value: wp
        - name: WORDPRESS_DB_PASSWORD
          value: secret
        - name: WORDPRESS_DB_NAME
          value: wordpress
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: blog
spec:
  containers:
    - name: wpdb
      image: mysql:latest
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wp
        - name: MYSQL_PASSWORD
          value: secret
