apiVersion: v1
kind: Pod
metadata:
  name: wordpress-standalone
spec:
  containers:
    - name: wp
      image: wordpress:latest
      env:
        - name: WORDPRESS_DB_HOST
          value: wpdb
        - name: WORDPRESS_DB_USER
          value: wp
        - name: WORDPRESS_DB_PASSWORD
          value: secret
        - name: WORDPRESS_DB_NAME
          value: wordpress
    - name: wpdb
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wp
        - name: MYSQL_PASSWORD
          value: secret
