apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: hala-majo-cambia-esto
  MYSQL_PASSWORD: clave_compartida_mysql_wp
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
stringData:
  WORDPRESS_DB_PASSWORD: clave_compartida_mysql_wp
