apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
data:
  WORDPRESS_DB_HOST: mariadb-service
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_NAME: wordpress
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wordpress
